/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

public class EmployeeWindow extends javax.swing.JFrame {
    Color c = new Color(150, 150, 255);

   
    public EmployeeWindow() {
        
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.setTitle("Employee Window");
        
        
        setIconImage(new ImageIcon(getClass().getResource("/Assets/iconoC.jpg")).getImage());
        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/Assets/employeeWindow1.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());

        this.getContentPane().setBackground(c);
        this.setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonInsertJanitor = new javax.swing.JButton();
        jButtonSeeInformation = new javax.swing.JButton();
        jButtonInsertAministrative = new javax.swing.JButton();
        jButtonInsertCarDriver = new javax.swing.JButton();
        jButtonInsertHMDriver = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonInsertJanitor.setBackground(new java.awt.Color(0, 0, 0));
        jButtonInsertJanitor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonInsertJanitor.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsertJanitor.setText("Insert Janitor");
        jButtonInsertJanitor.setBorder(null);
        jButtonInsertJanitor.setBorderPainted(false);
        jButtonInsertJanitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertJanitorActionPerformed(evt);
            }
        });

        jButtonSeeInformation.setBackground(new java.awt.Color(12, 12, 12));
        jButtonSeeInformation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonSeeInformation.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSeeInformation.setText(" Visualize Information");
        jButtonSeeInformation.setBorder(null);
        jButtonSeeInformation.setBorderPainted(false);
        jButtonSeeInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeInformationActionPerformed(evt);
            }
        });

        jButtonInsertAministrative.setBackground(new java.awt.Color(0, 0, 0));
        jButtonInsertAministrative.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonInsertAministrative.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsertAministrative.setText("Insert Administrative");
        jButtonInsertAministrative.setBorder(null);
        jButtonInsertAministrative.setBorderPainted(false);
        jButtonInsertAministrative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertAministrativeActionPerformed(evt);
            }
        });

        jButtonInsertCarDriver.setBackground(new java.awt.Color(0, 0, 0));
        jButtonInsertCarDriver.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonInsertCarDriver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsertCarDriver.setText("Insert Car Driver");
        jButtonInsertCarDriver.setBorder(null);
        jButtonInsertCarDriver.setBorderPainted(false);
        jButtonInsertCarDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertCarDriverActionPerformed(evt);
            }
        });

        jButtonInsertHMDriver.setBackground(new java.awt.Color(0, 0, 0));
        jButtonInsertHMDriver.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonInsertHMDriver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsertHMDriver.setText("Insert Heavy Machine Driver");
        jButtonInsertHMDriver.setBorder(null);
        jButtonInsertHMDriver.setBorderPainted(false);
        jButtonInsertHMDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertHMDriverActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setBorder(null);
        jButtonCancel.setBorderPainted(false);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonInsertAministrative, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jButtonInsertJanitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInsertCarDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInsertHMDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jButtonSeeInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonInsertJanitor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsertCarDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonInsertHMDriver, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jButtonInsertAministrative, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButtonSeeInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertAministrativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertAministrativeActionPerformed
        this.setVisible(false);
        InsertAdministrative ia= new InsertAdministrative();
        ia.setVisible(true);
    }//GEN-LAST:event_jButtonInsertAministrativeActionPerformed

    private void jButtonInsertJanitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertJanitorActionPerformed
        this.setVisible(false);
        InsertJanitor ijanitor= new InsertJanitor();
        ijanitor.setVisible(true);
    }//GEN-LAST:event_jButtonInsertJanitorActionPerformed

    private void jButtonInsertCarDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertCarDriverActionPerformed
        this.setVisible(false);
        InsertCarDriver icd= new InsertCarDriver();
        icd.setVisible(true);
    }//GEN-LAST:event_jButtonInsertCarDriverActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
        PrincipalWindow pw= new PrincipalWindow();
        pw.setVisible(true);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonInsertHMDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertHMDriverActionPerformed
        InsertHeavyMachineryDriver ihmd= new InsertHeavyMachineryDriver();
        ihmd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonInsertHMDriverActionPerformed

    private void jButtonSeeInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeInformationActionPerformed
        SeeEmployeeInformation see = null;
        try {
            see = new SeeEmployeeInformation();
        } catch (IOException ex) {
            Logger.getLogger(EmployeeWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EmployeeWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        see.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSeeInformationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonInsertAministrative;
    private javax.swing.JButton jButtonInsertCarDriver;
    private javax.swing.JButton jButtonInsertHMDriver;
    private javax.swing.JButton jButtonInsertJanitor;
    private javax.swing.JButton jButtonSeeInformation;
    // End of variables declaration//GEN-END:variables
}
