/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.Administrative;
import domain.CarDriver;
import domain.HeavyMachineryDriver;
import domain.Janitor;
import file.AdministrativeFile;
import java.awt.Color;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utility.Path;


public class InsertAdministrative extends javax.swing.JFrame {
    Color c= new Color(150,150,255);
    public static Vector administrativeVector;
    
    public InsertAdministrative() {
        Administrative adm1= new Administrative("Carlos","Perez","987", "3", true, "Bachillerato Universitario",2);
        this.setVisible(true);
        this.administrativeVector=new Vector(5);
        this.administrativeVector.addElement(adm1);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.setTitle("Insert Administrative");
        
        comboQualify.removeAllItems();
        comboQualify.addItem("Yes");
        comboQualify.addItem("No");
        
        comboCategory.removeAllItems();
        comboCategory.addItem("1");
        comboCategory.addItem("2");
        
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/Assets/image6.png"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());

        this.getContentPane().setBackground(c);
        this.setBackground(Color.BLACK);
    }

    public Vector getAdministrativeVector() {
        return administrativeVector;
    }

    public void setAdministrativeVector(Vector administrativeVector) {
        this.administrativeVector = administrativeVector;
    }
    
    public void addAdministrativeToVector(Administrative administrative){
        administrativeVector.addElement(administrative);
        JOptionPane.showMessageDialog(null,"The employee was inserted: "+administrative.toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlName = new javax.swing.JLabel();
        jlSurname = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();
        jlNumberOfEmployee = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jtfID = new javax.swing.JTextField();
        jtfNumberOfEmployee = new javax.swing.JTextField();
        jlCategory = new javax.swing.JLabel();
        jButtonInsert = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jlQualified = new javax.swing.JLabel();
        jtfSurname = new javax.swing.JTextField();
        jtfAcademyGrade = new javax.swing.JTextField();
        jlAcademyGrade = new javax.swing.JLabel();
        comboQualify = new javax.swing.JComboBox<>();
        comboCategory = new javax.swing.JComboBox<>();
        jbUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlName.setBackground(new java.awt.Color(51, 51, 0));
        jlName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlName.setForeground(new java.awt.Color(255, 255, 255));
        jlName.setText("Name:");

        jlSurname.setBackground(new java.awt.Color(51, 51, 0));
        jlSurname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlSurname.setForeground(new java.awt.Color(255, 255, 255));
        jlSurname.setText("Surname:");

        jlID.setBackground(new java.awt.Color(51, 51, 0));
        jlID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlID.setForeground(new java.awt.Color(255, 255, 255));
        jlID.setText("ID:");

        jlNumberOfEmployee.setBackground(new java.awt.Color(51, 51, 0));
        jlNumberOfEmployee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNumberOfEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jlNumberOfEmployee.setText("Number Employee:");

        jtfName.setBackground(new java.awt.Color(204, 204, 255));

        jtfID.setBackground(new java.awt.Color(204, 204, 255));

        jtfNumberOfEmployee.setBackground(new java.awt.Color(204, 204, 255));

        jlCategory.setBackground(new java.awt.Color(51, 51, 0));
        jlCategory.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlCategory.setForeground(new java.awt.Color(255, 255, 255));
        jlCategory.setText("Category:");

        jButtonInsert.setBackground(new java.awt.Color(0, 204, 204));
        jButtonInsert.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonInsert.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsert.setText("Get in");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(0, 204, 204));
        jButtonCancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jlQualified.setBackground(new java.awt.Color(51, 51, 0));
        jlQualified.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlQualified.setForeground(new java.awt.Color(255, 255, 255));
        jlQualified.setText("Qualify:");

        jtfSurname.setBackground(new java.awt.Color(204, 204, 255));

        jtfAcademyGrade.setBackground(new java.awt.Color(204, 204, 255));

        jlAcademyGrade.setBackground(new java.awt.Color(51, 51, 0));
        jlAcademyGrade.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlAcademyGrade.setForeground(new java.awt.Color(255, 255, 255));
        jlAcademyGrade.setText("Grado Academico");

        comboQualify.setBackground(new java.awt.Color(204, 204, 255));
        comboQualify.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboQualify.setBorder(null);

        comboCategory.setBackground(new java.awt.Color(204, 204, 255));
        comboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbUpdate.setBackground(new java.awt.Color(0, 204, 204));
        jbUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jbUpdate.setText("Update");
        jbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(369, Short.MAX_VALUE)
                        .addComponent(jbUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNumberOfEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfName, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(jtfSurname)
                                    .addComponent(jtfID)
                                    .addComponent(jtfNumberOfEmployee)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboQualify, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlAcademyGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jlName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jlSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                                            .addComponent(jlQualified, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jlCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfAcademyGrade, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                            .addComponent(comboCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(1, 1, 1)))))
                        .addGap(0, 290, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSurname)
                    .addComponent(jtfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlNumberOfEmployee)
                    .addComponent(jtfNumberOfEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQualified)
                    .addComponent(comboQualify, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCategory)
                            .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jtfAcademyGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlAcademyGrade, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonInsert)
                    .addComponent(jbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
      
        if (jtfName.getText().equals("") || jtfSurname.getText().equals("")
            || jtfID.getText().equals("") || jtfNumberOfEmployee.getText().equals("")
                || jtfAcademyGrade.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Error! There are blank spaces");//verifica espacios en blanco
        } else {
            try {
                boolean qualified;
                int category;
                if (comboQualify.getSelectedItem()=="Yes") {
                    qualified=true;
                } else {
                    qualified=false;
                }
                if (comboCategory.getSelectedItem()=="1") {
                    category=1;
                } else {
                    category=2;
                }//else catgory=2
                
                AdministrativeFile admFile = new AdministrativeFile(Path.my_adm_list_path);
                if (!admFile.getByIDBoolean(jtfID.getText())) {
                    try {
                        Administrative administrative=new Administrative(jtfName.getText(),jtfSurname.getText(),jtfID.getText(),jtfNumberOfEmployee.getText(), qualified,jtfAcademyGrade.getText(), category);
                        
                        admFile.saveAdministrative(administrative);
                        JOptionPane.showMessageDialog(null,"The employee "+jtfName.getText()+" has been inserted successfully");
                    } catch (IOException ex) {
                        Logger.getLogger(InsertAdministrative.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(InsertAdministrative.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "This ID already exists");
                }
            } //else
            catch (IOException ex) {
                Logger.getLogger(InsertAdministrative.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(InsertAdministrative.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        jtfName.setText("");
        jtfSurname.setText("");
        jtfID.setText("");
        jtfNumberOfEmployee.setText("");
        jtfAcademyGrade.setText("");
                
                                           
                //addAdministrativeToVector(administrative);
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
        EmployeeWindow emp= new EmployeeWindow();
        emp.setVisible(true);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateActionPerformed
        if (jtfName.getText().equals("") || jtfSurname.getText().equals("")
            || jtfID.getText().equals("") || jtfNumberOfEmployee.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Error! There are blank spaces");//verifica espacios en blanco
        } else { 
            try {
                boolean qualified;
                int category;
                if (comboQualify.getSelectedItem()=="Yes") {
                    qualified=true;
                } else {
                    qualified=false;
                }
                if (comboCategory.getSelectedItem()=="1") {
                    category=1;
                } else {
                    category=2;
                }//else catgory=2

                AdministrativeFile admFile = new AdministrativeFile(Path.my_adm_list_path);
                admFile.updateAdministrative(jtfName.getText(),jtfSurname.getText(),jtfID.getText(),jtfNumberOfEmployee.getText(),
                        qualified, jtfAcademyGrade.getText(),category);
                JOptionPane.showMessageDialog(null,"The employee has been updated");
            } catch (IOException ex) {
                Logger.getLogger(InsertAdministrative.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(InsertAdministrative.class.getName()).log(Level.SEVERE, null, ex);
            }
        }//if
    }//GEN-LAST:event_jbUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboCategory;
    private javax.swing.JComboBox<String> comboQualify;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jbUpdate;
    private javax.swing.JLabel jlAcademyGrade;
    private javax.swing.JLabel jlCategory;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlNumberOfEmployee;
    private javax.swing.JLabel jlQualified;
    private javax.swing.JLabel jlSurname;
    private javax.swing.JTextField jtfAcademyGrade;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfNumberOfEmployee;
    private javax.swing.JTextField jtfSurname;
    // End of variables declaration//GEN-END:variables
}
