/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.Administrative;
import domain.CarDriver;
import domain.HeavyMachineryDriver;
import domain.Janitor;
import file.AdministrativeFile;
import file.CarDriveFile;
import java.awt.Color;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import utility.Path;


public class InsertCarDriver extends javax.swing.JFrame {
    Color c= new Color(150,150,255);
    public static Vector carDriverVector;
    public InsertCarDriver() {
        this.setTitle("Insert Car Driver");
        CarDriver driver=new CarDriver( "Luis", "Perez","123", "2", true,"G1", 8, false,1);
        this.setVisible(true);
        this.carDriverVector=new Vector(5);
        this.carDriverVector.addElement(driver);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        comboLicense.removeAllItems();
        comboLicense.addItem("D3");//licencia maquinaria pesada
        comboLicense.addItem("B1");//licencia vehiculo
        
        comboTurn.removeAllItems();
        comboTurn.addItem("Day");
        comboTurn.addItem("Night");
        
        comboQualify.removeAllItems();
        comboQualify.addItem("Yes");
        comboQualify.addItem("No");
        
       
        
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/Assets/CarDriver1.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());

        this.getContentPane().setBackground(c);
        this.setBackground(Color.BLACK);
    }

    public Vector getCarDriverVector() {
        return carDriverVector;
    }

    public void setCarDriverVector(Vector carDriverVector) {
        this.carDriverVector = carDriverVector;
    }
    
    public void addCarDriverToVector(CarDriver cDriver){
        carDriverVector.addElement(cDriver);
        JOptionPane.showMessageDialog(null,"The employee was inserted: "+cDriver.toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlName = new javax.swing.JLabel();
        jlSurname = new javax.swing.JLabel();
        jlID = new javax.swing.JLabel();
        jlNumberOfEmployee = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jtfID = new javax.swing.JTextField();
        jtfNumberOfEmployee = new javax.swing.JTextField();
        jlWorkedHours = new javax.swing.JLabel();
        jtfWorkedHours = new javax.swing.JTextField();
        jlTurn = new javax.swing.JLabel();
        jlLicenseType = new javax.swing.JLabel();
        jButtonInsert = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jlQualified = new javax.swing.JLabel();
        jtfSurname = new javax.swing.JTextField();
        comboLicense = new javax.swing.JComboBox<>();
        comboTurn = new javax.swing.JComboBox<>();
        comboQualify = new javax.swing.JComboBox<>();
        jbUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlName.setBackground(new java.awt.Color(0, 0, 0));
        jlName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlName.setForeground(new java.awt.Color(255, 255, 255));
        jlName.setText("Nombre:");

        jlSurname.setBackground(new java.awt.Color(0, 0, 0));
        jlSurname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlSurname.setForeground(new java.awt.Color(255, 255, 255));
        jlSurname.setText("Apellido:");

        jlID.setBackground(new java.awt.Color(0, 0, 0));
        jlID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlID.setForeground(new java.awt.Color(255, 255, 255));
        jlID.setText("Cédula:");

        jlNumberOfEmployee.setBackground(new java.awt.Color(0, 0, 0));
        jlNumberOfEmployee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlNumberOfEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jlNumberOfEmployee.setText("Number Employee");

        jtfName.setBackground(new java.awt.Color(51, 51, 51));
        jtfName.setForeground(new java.awt.Color(255, 255, 255));
        jtfName.setBorder(null);

        jtfID.setBackground(new java.awt.Color(51, 51, 51));
        jtfID.setForeground(new java.awt.Color(255, 255, 255));
        jtfID.setBorder(null);

        jtfNumberOfEmployee.setBackground(new java.awt.Color(51, 51, 51));
        jtfNumberOfEmployee.setForeground(new java.awt.Color(255, 255, 255));
        jtfNumberOfEmployee.setBorder(null);

        jlWorkedHours.setBackground(new java.awt.Color(0, 0, 0));
        jlWorkedHours.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlWorkedHours.setForeground(new java.awt.Color(255, 255, 255));
        jlWorkedHours.setText("Worked Hours:");

        jtfWorkedHours.setBackground(new java.awt.Color(51, 51, 51));
        jtfWorkedHours.setForeground(new java.awt.Color(255, 255, 255));
        jtfWorkedHours.setBorder(null);
        jtfWorkedHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfWorkedHoursActionPerformed(evt);
            }
        });

        jlTurn.setBackground(new java.awt.Color(0, 0, 0));
        jlTurn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlTurn.setForeground(new java.awt.Color(255, 255, 255));
        jlTurn.setText("Turn:");

        jlLicenseType.setBackground(new java.awt.Color(0, 0, 0));
        jlLicenseType.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlLicenseType.setForeground(new java.awt.Color(255, 255, 255));
        jlLicenseType.setText(" Type of License:");

        jButtonInsert.setBackground(new java.awt.Color(0, 0, 0));
        jButtonInsert.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonInsert.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInsert.setText("Get In");
        jButtonInsert.setBorder(null);
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancel.setText("Cancel");
        jButtonCancel.setBorder(null);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jlQualified.setBackground(new java.awt.Color(0, 0, 0));
        jlQualified.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlQualified.setForeground(new java.awt.Color(255, 255, 255));
        jlQualified.setText("Qualify:");

        jtfSurname.setBackground(new java.awt.Color(51, 51, 51));
        jtfSurname.setForeground(new java.awt.Color(255, 255, 255));
        jtfSurname.setBorder(null);

        comboLicense.setBackground(new java.awt.Color(0, 0, 0));
        comboLicense.setForeground(new java.awt.Color(255, 255, 255));
        comboLicense.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLicenseActionPerformed(evt);
            }
        });

        comboTurn.setBackground(new java.awt.Color(0, 0, 0));
        comboTurn.setForeground(new java.awt.Color(255, 255, 255));
        comboTurn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboQualify.setBackground(new java.awt.Color(0, 0, 0));
        comboQualify.setForeground(new java.awt.Color(255, 255, 255));
        comboQualify.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbUpdate.setBackground(new java.awt.Color(0, 0, 0));
        jbUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jbUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jbUpdate.setText("Update");
        jbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlWorkedHours, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jlSurname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                    .addComponent(jlID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addComponent(jlName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jlNumberOfEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfSurname, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jtfName)
                                    .addComponent(jtfID)
                                    .addComponent(jtfWorkedHours)
                                    .addComponent(jtfNumberOfEmployee)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlLicenseType, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlQualified, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboQualify, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlWorkedHours, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfWorkedHours, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNumberOfEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNumberOfEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlLicenseType, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboLicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTurn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlQualified, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboQualify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        
         if (jtfName.getText().equals("") || jtfSurname.getText().equals("")
            || jtfID.getText().equals("") || jtfNumberOfEmployee.getText().equals("") 
            || jtfWorkedHours.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Error! There are blank spaces");//verifica espacios en blanco
        } else {
             try {
                 boolean qualified;
                 boolean turn;
                 if (comboQualify.getSelectedItem()=="Yes") {
                     qualified=true;
                 } else {
                     qualified=false;
                 }
                 if (comboTurn.getSelectedItem()=="Day") {
                     turn=true;
                 } else {
                     turn=false;
                 }
                 
                 CarDriveFile carFile = new CarDriveFile(Path.my_carDriver_list_path);
                 if (!carFile.getByIDBoolean(jtfID.getText())) {
                     try {
                         CarDriver carDriver= new CarDriver( jtfName.getText(), jtfSurname.getText(), jtfID.getText()
                                 , jtfNumberOfEmployee.getText(), qualified,(String) comboLicense.getSelectedItem(),
                                 Integer.parseInt(jtfWorkedHours.getText())
                                 , turn, 1);
                         
                         carFile.saveCarDriver(carDriver);
                         JOptionPane.showMessageDialog(null,"The employee "+jtfName.getText()+" has been inserted successfully");
                     } catch (IOException ex) {
                         Logger.getLogger(InsertCarDriver.class.getName()).log(Level.SEVERE, null, ex);
                     } catch (ClassNotFoundException ex) {
                         Logger.getLogger(InsertCarDriver.class.getName()).log(Level.SEVERE, null, ex);
                     }
                 } else {
                     JOptionPane.showMessageDialog(null, "This ID already exists");
                 }
             } catch (IOException ex) {
                 Logger.getLogger(InsertCarDriver.class.getName()).log(Level.SEVERE, null, ex);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(InsertCarDriver.class.getName()).log(Level.SEVERE, null, ex);
             }
         }
        jtfName.setText("");
        jtfSurname.setText("");
        jtfID.setText("");
        jtfNumberOfEmployee.setText("");
        jtfWorkedHours.setText("");
                
       
        //addCarDriverToVector(carDriver);
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
        EmployeeWindow emp= new EmployeeWindow();
        emp.setVisible(true);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jtfWorkedHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfWorkedHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfWorkedHoursActionPerformed

    private void comboLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLicenseActionPerformed

    private void jbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUpdateActionPerformed
        if (jtfName.getText().equals("") || jtfSurname.getText().equals("")
            || jtfID.getText().equals("") || jtfNumberOfEmployee.getText().equals("") 
            || jtfWorkedHours.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Error! There are blank spaces");//verifica espacios en blanco
        } else {
            try {
                boolean qualified;
                boolean turn;
                if (comboQualify.getSelectedItem()=="Yes") {
                    qualified=true;
                } else {
                    qualified=false;
                }
                if (comboTurn.getSelectedItem()=="Day") {
                    turn=true;
                } else {
                    turn=false;
                }
                CarDriveFile carFile = new CarDriveFile(Path.my_carDriver_list_path);
                carFile.updateCarDriver( jtfName.getText(), jtfSurname.getText(), jtfID.getText()
                        , jtfNumberOfEmployee.getText(), qualified,(String) comboLicense.getSelectedItem(),
                        Integer.parseInt(jtfWorkedHours.getText())
                        , turn, 1);
                JOptionPane.showMessageDialog(null,"The employee has been updated");
            } catch (IOException ex) {
                Logger.getLogger(InsertCarDriver.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(InsertCarDriver.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboLicense;
    private javax.swing.JComboBox<String> comboQualify;
    private javax.swing.JComboBox<String> comboTurn;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jbUpdate;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlLicenseType;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlNumberOfEmployee;
    private javax.swing.JLabel jlQualified;
    private javax.swing.JLabel jlSurname;
    private javax.swing.JLabel jlTurn;
    private javax.swing.JLabel jlWorkedHours;
    private javax.swing.JTextField jtfID;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfNumberOfEmployee;
    private javax.swing.JTextField jtfSurname;
    private javax.swing.JTextField jtfWorkedHours;
    // End of variables declaration//GEN-END:variables
}
