/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

public class PrincipalWindow extends javax.swing.JFrame {
    Color c = new Color(150, 150, 255);

    /**
     * Creates new form PrincipalWindow
     */
    public PrincipalWindow() {
        this.setTitle("Principal Window");
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        
        setIconImage(new ImageIcon(getClass().getResource("/Assets/iconoC.jpg")).getImage());
        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon uno = new ImageIcon(this.getClass().getResource("/Assets/imagen1.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());

        this.getContentPane().setBackground(c);
        this.setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVehicle = new javax.swing.JButton();
        jButtonEmployee = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonVehicle.setBackground(new java.awt.Color(0, 0, 0));
        jButtonVehicle.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jButtonVehicle.setForeground(new java.awt.Color(0, 204, 204));
        jButtonVehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/vehicle.png"))); // NOI18N
        jButtonVehicle.setText("Vehicles");
        jButtonVehicle.setBorder(null);
        jButtonVehicle.setBorderPainted(false);
        jButtonVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVehicleActionPerformed(evt);
            }
        });

        jButtonEmployee.setBackground(new java.awt.Color(0, 0, 0));
        jButtonEmployee.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jButtonEmployee.setForeground(new java.awt.Color(0, 204, 204));
        jButtonEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/employee4.png"))); // NOI18N
        jButtonEmployee.setText("Employees");
        jButtonEmployee.setBorder(null);
        jButtonEmployee.setBorderPainted(false);
        jButtonEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmployeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEmployee)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVehicleActionPerformed
        VehicleWindow vehicleWindow=new VehicleWindow();
        vehicleWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVehicleActionPerformed

    private void jButtonEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmployeeActionPerformed
        EmployeeWindow employee=new EmployeeWindow();
        employee.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEmployeeActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEmployee;
    private javax.swing.JButton jButtonVehicle;
    // End of variables declaration//GEN-END:variables
}
